services:
  websockets:
    build:
      context: .
      dockerfile: Dockerfile.websockets
    ports:
      - "8887:8887"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"