# Use an official Node.js runtime as a parent image
FROM node

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
# COPY package*.json ./

# Install app dependencies
RUN npm install ws redis

# Bundle app source
COPY . .

# Start the application
CMD ["node", "index.mjs"]
# CMD ["sleep", "infinity"]